# Generated by Django 3.1.1 on 2020-11-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_watering'),
    ]

    operations = [
        migrations.AddField(
            model_name='watering',
            name='water',
            field=models.CharField(choices=[('O', 'Once a Week'), ('T', 'Twice a Week')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='watering',
            name='date',
            field=models.DateField(verbose_name='Watering Date'),
        ),
    ]
